- name: desable default nodejs
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf: # only works for Redhat family
    name: "{{ item }}"
    state: installed
  loop:
  - nodejs
  - mysql

- name: create expense user
  ansible.builtin.user:
    name: expense

- name: run app pre-requisites
  tags:
  - deployment
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

# - name: create app directory
#   ansible.builtin.file:
#     path: /app
#     state: directory

# - name: download backend code
#   ansible.builtin.get_url:
#     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
#     dest: /tmp/backend.zip

# - name: unzip backend code
#   ansible.builtin.unarchive:
#     src: /tmp/backend.zip # by default checks in ansible server
#     dest: /app
#     remote_src: yes

- name: install npm dependencies
  tags:
  - deployment                            ## we are using this tags to run this specific tasks in this whole tasks
  ansible.builtin.command: npm install    ## mention it in the ansible commadnd
  args:
    chdir: /app

- name: copy backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service
  notify: 
  - daemon reload

- name: install python dependencies
  ansible.builtin.pip:
    name: 
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import data into mysql
  community.mysql.mysql_db:
    login_host: "{{ login_host }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    target: /app/schema/backend.sql
    state: import
    name: all


# written handlers for this
# - name: daemon reload
#   ansible.builtin.systemd_service:
#     daemon_reload: true

- name: start and enable backend service
  tags: 
    - deployment
  ansible.builtin.service:
    name: backend
    state: restarted
    enabled: yes